### ISSUE TITLE
no context on python3

### ISSUE THREAD

**Issue by CastixGitHub** [TurboGears/tg2#99]
I've a tg2.3 app that runs perfectly on python 2.7 but I tried it with python 3.6.5 and I got this traceback
```
17:29:44,553 WARNI [py.warnings] /home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/gearbox/main.py:159: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  if 'cmd_name' in inspect.getargspec(cmd_factory.__init__).args:

17:29:44,553 INFO  [gearbox] Starting subprocess with file monitor
17:29:44,958 WARNI [py.warnings] /home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/gearbox/main.py:159: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  if 'cmd_name' in inspect.getargspec(cmd_factory.__init__).args:

17:29:45,023 WARNI [py.warnings] /home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/pymongo/pool.py:124: PendingDeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
  platform.linux_distribution() if part])),

17:29:45,237 WARNI [py.warnings] /home/castix/axant/myproject/myproject/venv3/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)

17:29:45,279 WARNI [py.warnings] /home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/tg/configuration/app_config.py:311: DeprecationWarning: AppConfig.register_hook is deprecated, please use tg.hooks.register and AppConfig.register_controller_wrapper instead
  "AppConfig.register_controller_wrapper instead", DeprecationWarning)

17:29:45,279 INFO  [tgext.pluggable] Plugging tgappcategories
17:29:45,280 INFO  [tgext.pluggable] Plugging tgapppermissions
17:29:45,280 INFO  [tgext.pluggable] Plugging registration
17:29:45,280 INFO  [tgext.pluggable] Plugging tgext.mailer
17:29:45,282 INFO  [tgext.pluggable] Plugging invitations
17:29:45,283 INFO  [tgext.pluggable] Plugging resetpassword
17:29:45,283 INFO  [tgext.pluggable] Plugging userprofile
17:29:45,283 INFO  [tgext.pluggable] Plugging tgcomments
17:29:45,283 INFO  [tgext.pluggable] Plugging flatpages
17:29:45,284 INFO  [tgext.pluggable] Plugging fbauth
17:29:45,284 INFO  [tgext.pluggable] Plugging googleplusauth
17:29:45,284 INFO  [tgext.pluggable] Plugging activitystream
17:29:45,285 INFO  [tgext.pluggable] Plugging tgext.evolve
17:29:45,285 INFO  [tgext.evolve] Setting up tgext.evolve extension...
17:29:45,308 INFO  [tgext.pluggable] Plugging tgext.celery
17:29:45,308 INFO  [tgext.celery] Setting up tgext.celery extension...
17:29:45,308 INFO  [tgext.pluggable] Plugging mailtemplates
17:29:45,324 INFO  [tgapp-mailtemplates] Configuring MailTemplates for Ming
17:29:45,326 INFO  [tgext.webassets] Setting up tgext.webassets extension...
17:29:45,328 INFO  [flatpages.model] Configuring FlatPages for Ming
17:29:45,336 INFO  [tgcomments.model] Configuring TGComments for Ming
17:29:45,337 INFO  [userprofile.model] Configuring tgapp-userprofile for Ming
17:29:45,338 INFO  [invitations.model] Configuring Invitations for Ming
17:29:45,339 INFO  [tgapppermissions] Configuring TgappPermissions for Ming
17:29:45,339 INFO  [tgappcategories] Configuring TgappCategories for Ming
17:29:45,340 INFO  [myproject.depot] Configuring Storage depot.post_images.*
17:29:45,340 INFO  [myproject.depot] Configuring Storage depot.tg_user_avatars.*
17:29:45,340 INFO  [myproject.depot] Configuring Storage depot.tg_user_profile_covers.*
17:29:45,340 INFO  [myproject.depot] Configuring Storage depot.post_videos.*
17:29:45,345 WARNI [py.warnings] /home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/boto/plugin.py:40: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp

17:29:45,862 INFO  [myproject.depot] Configuring Storage depot.category_images.*
17:29:45,862 INFO  [myproject.depot] Configuring Storage depot.actual_tag_images.*
17:29:45,863 INFO  [myproject.depot] Configuring Storage depot.flatpages_flatfiles.*
17:29:45,905 WARNI [py.warnings] /home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/sprox/validators.py:17: DeprecationWarning: _to_python is deprecated; use _convert_to_python instead
  class UniqueValue(FancyValidator):

17:29:45,914 WARNI [py.warnings] /home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/tgext/datahelpers/validators.py:84: DeprecationWarning: _to_python is deprecated; use _convert_to_python instead
  class MingEntityConverter(FancyValidator):

17:29:45,914 WARNI [py.warnings] /home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/tgext/datahelpers/validators.py:84: DeprecationWarning: _from_python is deprecated; use _convert_from_python instead
  class MingEntityConverter(FancyValidator):

17:29:45,914 WARNI [py.warnings] /home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/tgext/datahelpers/validators.py:84: DeprecationWarning: validate_python is deprecated; use _validate_python instead
  class MingEntityConverter(FancyValidator):

17:29:45,958 WARNI [py.warnings] /home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/invitations/lib/__init__.py:29: DeprecationWarning: validate_python is deprecated; use _validate_python instead
  _module = __import__(_module, fromlist=_form_name)

17:29:45,966 WARNI [py.warnings] /home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/registration/lib/__init__.py:28: DeprecationWarning: validate_python is deprecated; use _validate_python instead
  module = __import__(module, fromlist=form_name)

17:29:46,012 WARNI [py.warnings] /home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/ming/metadata.py:365: DeprecationWarning: ensure_index is deprecated. Use create_index instead.
  **idx.index_options)

17:29:46,018 WARNI [py.warnings] /home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/ming/session.py:111: DeprecationWarning: ensure_index is deprecated. Use create_index instead.
  return self._impl(cls).ensure_index(index_fields, **kwargs), fields

17:29:46,025 WARNI [py.warnings] /home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/tg/configuration/app_config.py:925: DeprecationWarning: controller wrappers should be registered on AppConfig using AppConfig.register_controller_wrapper
  milestones.environment_loaded.reach()

17:29:46,025 INFO  [tgext.evolve] tgext.evolve enabled: True
17:29:46,025 INFO  [tgext.evolve] Configuring tgext.evolve for Ming
17:29:46,026 INFO  [tgext.mailer] Configured Mailer
17:29:46,026 WARNI [py.warnings] /home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/tgext/evolve/ming_evolver.py:22: DeprecationWarning: ensure_index is deprecated. Use create_index instead.
  col.ensure_index('type', background=False, unique=True)

17:29:46,027 WARNI [py.warnings] /home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/tgext/evolve/ming_evolver.py:29: DeprecationWarning: find_and_modify is deprecated, use find_one_and_delete, find_one_and_replace, or find_one_and_update instead
  upsert=True)

17:29:46,028 INFO  [tgext.evolve] Process 6619, running evolutions after AdjustPermissions
17:29:46,028 WARNI [py.warnings] /home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/tgext/evolve/ming_evolver.py:38: DeprecationWarning: find_and_modify is deprecated, use find_one_and_delete, find_one_and_replace, or find_one_and_update instead
  new=True)

17:29:46,029 INFO  [tgext.evolve] Evolutions Completed
17:29:46,034 WARNI [py.warnings] /home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/backlash/tbtools.py:26: DeprecationWarning: Flags not at the start of the expression '^(.*?)$(?m)'
  _line_re = re.compile(r'^(.*?)$(?m)')

17:29:46,035 INFO  [tgapp-registration] initializing registration with ming
17:29:46,059 ERROR [gearbox] Failed to load application or server
17:29:46,059 ERROR [gearbox] No object (name: context) has been registered for this thread
Traceback (most recent call last):
  File "/home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/gearbox/main.py", line 167, in _run_subcommand
    return cmd.run(parsed_args)
  File "/home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/gearbox/command.py", line 31, in run
    self.take_action(parsed_args)
  File "/home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/gearbox/commands/serve.py", line 254, in take_action
    relative_to=base, global_conf=parsed_vars)
  File "/home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/gearbox/commands/serve.py", line 289, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/paste/deploy/util.py", line 58, in fix_call
    reraise(*exc_info)
  File "/home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/paste/deploy/compat.py", line 32, in reraise
    raise e.with_traceback(tb)
  File "/home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/castix/axant/myproject/myproject/myproject/config/middleware.py", line 33, in make_app
    app = make_base_app(global_conf, full_stack=True, **app_conf)
  File "/home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/tg/configuration/app_config.py", line 1298, in make_base_app
    app = tg.hooks.notify_with_value('after_config', app)
  File "/home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/tg/configuration/hooks.py", line 136, in notify_with_value
    value = func(value)
  File "/home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/tgext/pluggable/adapt_controllers.py", line 32, in mount_controllers
    mountpoint, name = self._resolve_mountpoint(app_id)
  File "/home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/tgext/pluggable/adapt_controllers.py", line 16, in _resolve_mountpoint
    root = tgapp.find_controller('root')
  File "/home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/tg/wsgiapp.py", line 253, in find_controller
    mycontroller = self.lookup_controller(self.config, controller)
  File "/home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/tg/wsgiapp.py", line 235, in lookup_controller
    __import__(full_module_name)
  File "/home/castix/axant/myproject/myproject/myproject/controllers/root.py", line 17, in <module>
    from myproject.controllers.post.post import PostsController
  File "/home/castix/axant/myproject/myproject/myproject/controllers/post/post.py", line 3, in <module>
    from myproject.controllers.post.link import PostLinkController
  File "/home/castix/axant/myproject/myproject/myproject/controllers/post/link.py", line 45, in <module>
    class PostLinkController(BaseController):
  File "/home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/tg/controllers/decoratedcontroller.py", line 34, in __init__
    if hasattr(value, 'decoration') and value.decoration.inherit:
  File "/home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/tg/util/lazystring.py", line 30, in __getattr__
    return getattr(self.eval(), attr)
  File "/home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/tg/util/lazystring.py", line 15, in eval
    return self.func(*self.args, **self.kwargs)
  File "/home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/tg/i18n.py", line 87, in ugettext
    return tg.translator.gettext(value)
  File "/home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/tg/support/objectproxy.py", line 19, in __getattr__
    return getattr(self._current_obj(), attr)
  File "/home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/tg/request_local.py", line 214, in _current_obj
    return getattr(context, self.name)
  File "/home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/tg/support/objectproxy.py", line 19, in __getattr__
    return getattr(self._current_obj(), attr)
  File "/home/castix/axant/myproject/myproject/venv3/lib/python3.6/site-packages/tg/support/registry.py", line 72, in _current_obj
    'thread' % self.____name__)
TypeError: No object (name: context) has been registered for this thread
sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=4, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.0.0.112', 54808), raddr=('52.216.16.0', 443)>
```
As it's not so important for me to bring the app to python3 for now I didn't invest much effort searching what causes this issue, but it seems to be an issue of tg itself as I don't see any other error

**Comment by amol-** [comment]
It looks like it's cause by some class property (An attribute of `PostLinkController`) that is an instance of `lazy_ugettext` so when the controller gets inspected to apply exposition inheritance the translation of such property gets triggered but can't proceed because it's outside of a request.
